services:
  # Frontend Service (React/Vite)
  - type: web
    name: frontend
    env: docker
    buildCommand: npm install && npm run build  # Build the frontend first
    startCommand: nginx -g "daemon off;"  # Nginx will serve the built frontend
    dockerfilePath: ./frontend/Dockerfile  # Path to the Dockerfile for the frontend
    staticPublishPath: /usr/share/nginx/html  # The directory Nginx will serve
    envVars:
      - key: NGINX_HOST
        value: https://texttoimageproject-frontend.onrender.com
    autoDeploy: true

  # Backend Service (Node.js API)
  - type: websh
    name: backend
    env: docker
    buildCommand: npm install
    startCommand: node index.js
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 5000
    autoDeploy: true

  # Nginx Service (To serve the frontend and proxy to backend)
  - type: web
    name: nginx
    env: docker
    dockerfilePath: ./nginx/Dockerfile  # Path to the Nginx Dockerfile
    envVars:
      - key: BACKEND_URL
        value: https://texttoimageproject-backend.onrender.com  # Ensure this is correct for proxying to your backend
    autoDeploy: true
