services:
  # Frontend as a static site
  - type: static_site
    name: frontend
    buildCommand: npm install && npm run build  # Build the React app (Vite)
    publishDirectory: ./dist  # Directory containing static files (after build)
    autoDeploy: true  # Automatically deploy on push to GitHub

  # Backend Service
  - type: web
    name: backend
    env: docker
    buildCommand: npm install                 # Install backend dependencies
    startCommand: node index.js               # Start the backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 5000                           # Ensure the backend runs on port 5000
    autoDeploy: true

  # Nginx Service (Serve frontend and proxy API requests)
  - type: web
    name: nginx
    env: docker
    buildCommand: npm install && npm run build  # Build frontend before starting Nginx (Note: this might not be necessary for Nginx)
    startCommand: nginx -g "daemon off;"        # Start Nginx
    dockerfilePath: ./nginx/Dockerfile
    autoDeploy: true
    dependsOn:
      - frontend
      - backend   # Ensure Nginx starts only after frontend and backend are ready
